#!/usr/bin/env python3

import colors as c
import time

count_length = 0.500

try:
    while True:
        for n in range(16):
            string = '{:2} {:04b} {:x}' .format(n,n,n).upper()
            print(c.cl + c.r + string + c.x)
            time.sleep(count_length)

except KeyboardInterrupt:
  exit(0)
