#!/usr/bin/env python3

import colors as c
import random as random
print(c.clear)

sides = []


sides.append(c.r + "1" + c.x) 
sides.append(c.o + "2" + c.x)
sides.append(c.b + "3" + c.x)
sides.append(c.c + "4" + c.x)
sides.append(c.g + "5" + c.x)
sides.append(c.y + "6" + c.x) 

while True:
    side = random.choice(sides)
    print("rolled: " + side)
    input()

# sides = ["1","2","3","4","5","6"]

# for side in sides:
#  print("no index needed for", side)

# for n in range(6):
#     print("index, n, "is side", sides[n])

# n = 0
# while n < 6:
#       print("index", n, "is side", sides[n])
#       n = n + 1 
