#!/usr/bin/env python3

import colors as c
import random


print(c.clear)

sides = []

sides.append('''
  -------
 |       |
 |   o   |
 |       |
  -------
  ''')

sides.append('''
    -------
   | o     |
   |       |
   |     o | 
    -------
    ''')

sides.append('''
      -------
     | o     |
     |   o   |
     |     o |
      -------
      ''')

sides.append('''
        -------
       | o   o |
       |       |
       | o   o |
        -------
        ''')

sides.append('''
          -------
         | o   o |
         |   o   |
         | o   o |
          -------
          ''')

sides.append('''
            -------
           | o   o |
           | o   o |
           | o   o |
            -------
            ''')

while True:
    side = random.choice(sides)
    print(c.cl + c.rc() + side + c.x)
    print(c.green + "                           Press E and enter any time to exit" + c.x)
    print(c.b + "                                Press enter to re-roll die" + c.x)
    e = input()
    if e == "e" or e == "E":
        exit()

